# Location of secrets in google cloud
secrets:
  key_template: projects/76139268481/secrets/{key_name}/versions/latest
  account_sid_key: twilio_ACCOUNT_SID
  auth_token_key: twilio_AUTH_TOKEN
  mission_email: MISSION_EMAIL
  oauth_secret: email2missionOauth_client_secret

twilio:
  purchased_phone_number: +14069241940
  call_script_url: https://handler.twilio.com/twiml/EH1dd19d1980e983d0ffbad12486659c20?description={}&needForAction={}
  text_delay: 30 # seconds. Used to give head start to cloud messages