# Location of secrets in google cloud
secrets:
  project_id: 76139268481

twilio:
  purchased_phone_number: +14069241940
  call_script_url: https://handler.twilio.com/twiml/EH1dd19d1980e983d0ffbad12486659c20?description={}&needForAction={}
  text_delay: 30 # seconds. Used to give head start to cloud messages

email_2_mission:
  topic: projects/missionout/topics/new_mission

firestore_document_paths:
  mission_path : 'teams/{team_Id}/missions'
  page_path : '{mission_path}/{mission_id}/pages'
  team_path : teams
  users : users